version: "3"
services:
    mongodb:
        image: mongo
        restart: always
    node-server:
        depends_on:
            - mongodb
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./server:/app
        ports:
            - 5000:5000
        environment:
            - MONGO_URI=mongodb
            - MONGO_PORT=27017
